import type { H3Event } from 'h3'

// KVNamespace, D1Database, WorkerLoader, WorkerLoaderWorkerCode, WorkerStub, SendEmail, and
// AnalyticsEngineDataset below are global ambient types from
// server/types/worker-configuration.d.ts (generated by `pnpm run cf-typegen`) — no import
// needed. See server/types/cloudflare-bindings.d.ts for what's still hand-written.

interface CfBindings {
  kv: KVNamespace | null
  loader: WorkerLoader | null
  r2: R2Bucket | null
}

// Module-level fallback caches, one per binding — mirrors the singleton pattern in
// server/middleware/01.d1-cache.ts (which does the same thing for the D1 binding via
// useDb()): Cloudflare bindings are only present on `event.context.cloudflare.env` for a
// real incoming request, but some code paths (rare, but real: an isolate reused across
// requests hitting a code path where the event's own env is momentarily unavailable) need a
// last-known-good binding rather than failing outright. Populated on every call that does
// have a live `env`, read as a fallback on calls that don't.
let _kv: KVNamespace | null = null
let _loader: WorkerLoader | null = null
let _r2: R2Bucket | null = null

export function getCfBindings(event: H3Event): CfBindings {
  const env = event?.context?.cloudflare?.env
  if (env?.PLUGIN_KV) _kv = env.PLUGIN_KV as KVNamespace
  if (env?.LOADER) _loader = env.LOADER as WorkerLoader
  if (env?.MEDIA_BUCKET) _r2 = env.MEDIA_BUCKET as R2Bucket

  return {
    kv: (env?.PLUGIN_KV as KVNamespace | undefined) ?? _kv ?? null,
    loader: (env?.LOADER as WorkerLoader | undefined) ?? _loader ?? null,
    r2: (env?.MEDIA_BUCKET as R2Bucket | undefined) ?? _r2 ?? null,
  }
}

/**
 * Registers a non-critical-path promise (push notification, best-effort email, etc.) with
 * the Worker's `ctx.waitUntil()` so it keeps running after the response is sent, instead of
 * being silently cancelled. An un-awaited, un-registered promise in workerd is only
 * guaranteed to run until the response is returned — once the isolate is free to be
 * reused for the next request, an in-flight fire-and-forget promise can be torn down
 * before it resolves, and its `.catch()` never even runs, so the failure isn't just
 * unhandled, it's invisible. Falls back to awaiting inline wherever `ctx.waitUntil` isn't
 * present (unit/integration tests, non-Workers environments), matching the equivalent
 * fallback in `withEdgeCache`.
 */
export function waitUntil(event: H3Event, promise: Promise<unknown>): void {
  const ctx = event.context.cloudflare?.ctx
  if (ctx?.waitUntil) {
    ctx.waitUntil(promise)
  } else {
    void promise
  }
}

export function getAnalyticsEngine(event: H3Event): AnalyticsEngineDataset | null {
  return (event?.context?.cloudflare?.env?.AE as AnalyticsEngineDataset | undefined) ?? null
}

/**
 * Cloudflare's native transactional email binding — no API key, sends from any domain
 * onboarded via `wrangler email sending enable <domain>`. See server/utils/email.ts.
 */
export function getEmailBinding(event: H3Event): SendEmail | null {
  return (event?.context?.cloudflare?.env?.EMAIL as SendEmail | undefined) ?? null
}

/**
 * Workers AI binding — no API key, no account setup beyond declaring the binding in
 * wrangler.toml. See server/utils/ai-sdk.ts's `workers-ai` provider branch and
 * server/utils/image-providers/workers-ai.ts.
 */
export function getWorkersAiBinding(event: H3Event): Ai | null {
  return (event?.context?.cloudflare?.env?.AI as Ai | undefined) ?? null
}

/**
 * Vectorize index binding for semantic search / RAG embeddings. Null when the site hasn't
 * provisioned a Vectorize index (it's opt-in — see wrangler.toml.example) — every caller
 * treats null as "semantic search unavailable, fall back to FTS5 only" rather than throwing.
 */
export function getVectorizeIndex(event: H3Event): VectorizeIndex | null {
  return (event?.context?.cloudflare?.env?.VECTORIZE as VectorizeIndex | undefined) ?? null
}
