import type { H3Event } from 'h3'
import { getCfBindings } from './cf-env'

// KVNamespace, WorkerLoader, WorkerLoaderWorkerCode, and WorkerStub below are global
// ambient types from server/types/worker-configuration.d.ts (generated by
// `pnpm run cf-typegen`) — no import needed. See server/types/cloudflare-bindings.d.ts
// for what's still hand-written.

export async function getPluginServerCode(event: H3Event, siteId: string, pluginId: string): Promise<string | null> {
  const { kv } = getCfBindings(event)
  if (!kv) return null
  return kv.get(`plugin:${siteId}:${pluginId}:server`)
}

export async function getPluginClientBundle(event: H3Event, siteId: string, pluginId: string): Promise<string | null> {
  const { kv } = getCfBindings(event)
  if (!kv) return null
  return kv.get(`plugin:${siteId}:${pluginId}:client`)
}

export async function putPluginServerCode(event: H3Event, siteId: string, pluginId: string, code: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) throw createError({ statusCode: 503, message: 'Dynamic plugins require a Cloudflare KV namespace (PLUGIN_KV). Configure it in wrangler.toml.' })
  await kv.put(`plugin:${siteId}:${pluginId}:server`, code)
}

export async function putPluginClientBundle(event: H3Event, siteId: string, pluginId: string, bundle: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) throw createError({ statusCode: 503, message: 'Dynamic plugins require a Cloudflare KV namespace (PLUGIN_KV). Configure it in wrangler.toml.' })
  await kv.put(`plugin:${siteId}:${pluginId}:client`, bundle)
}

export async function deletePluginAssets(event: H3Event, siteId: string, pluginId: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) return
  await Promise.all([
    kv.delete(`plugin:${siteId}:${pluginId}:server`),
    kv.delete(`plugin:${siteId}:${pluginId}:client`),
  ])
}

// A plugin is third-party code: Ed25519-signature-verified and checksum-matched at
// install/request time (see assertCodeIntegrity() call sites), which proves *authorship
// consistency*, not that the code is benign or bug-free. Without an explicit `limits`, a
// dynamic Worker runs under the parent request's own plan-standard CPU/subrequest budget —
// a runaway loop or accidental infinite-recursion bug in plugin code would burn CPU time
// against (and could starve) the request that spawned it. `cpuMs: 50` is generous for the
// kind of request/response logic plugin server modules actually do (no DB access, no
// outbound network — see globalOutbound below — so there's nothing legitimately slow to
// wait on) while still bounding a runaway loop to a small, fixed cost. `subRequests: 10` is
// mostly a defensive floor rather than a number plugins are expected to approach: with
// `globalOutbound: null` blocking all outbound fetch()/connect(), a plugin has no bindings
// to make subrequests against today, but the limit still guards against future capability
// additions or an internal-fetch edge case rather than leaving it uncapped.
// Set on *both* the WorkerLoaderWorkerCode (below) and the getEntrypoint() call at the
// fetch call site (server/routes/_nuxflow/ext/[pluginId]/[...path].ts) — per Cloudflare's
// docs the lower of the two wins, so this is belt-and-suspenders in case either call site
// is ever changed independently.
// See https://developers.cloudflare.com/dynamic-workers/usage/limits/ and
// https://developers.cloudflare.com/dynamic-workers/usage/egress-control/.
export const PLUGIN_WORKER_LIMITS: { cpuMs: number, subRequests: number } = {
  cpuMs: 50,
  subRequests: 10,
}

// No bindings/secrets are passed to the spawned worker (the returned WorkerLoaderWorkerCode
// carries no `env`), and `globalOutbound: null` additionally blocks all outbound fetch()/
// connect() from plugin code — a plugin can only use whatever the platform gives it, nothing
// external. See https://developers.cloudflare.com/dynamic-workers/usage/egress-control/.
export function spawnPluginWorker(
  event: H3Event,
  cacheId: string,
  getCode: () => Promise<string>,
): WorkerStub {
  const { loader } = getCfBindings(event)
  if (!loader) throw createError({ statusCode: 503, message: 'Dynamic Workers (LOADER binding) are not available in this environment.' })

  return loader.get(cacheId, async (): Promise<WorkerLoaderWorkerCode> => {
    const code = await getCode()
    return {
      compatibilityDate: '2026-04-01',
      mainModule: 'index.js',
      modules: { 'index.js': code },
      globalOutbound: null,
      limits: PLUGIN_WORKER_LIMITS,
    }
  })
}
