import type { H3Event } from 'h3'
import { sanitizeThemeCss } from './security'
import { getCachedThemeCss, setCachedThemeCss, clearCachedThemeCss } from './theme-cache'
import { useDb } from './db'
import { getCfBindings } from './cf-env'
import { themes } from '@nuxflow/db/schema'
import { and, eq, sql } from 'drizzle-orm'

// KVNamespace below is a global ambient type from
// server/types/worker-configuration.d.ts (generated by `pnpm run cf-typegen`) — no
// import needed. See server/types/cloudflare-bindings.d.ts for what's still hand-written.

// KV key includes the theme row's cssVersion — see the comment on `themes.cssVersion` in
// packages/db/src/schema/system.ts for why a version bump (rather than overwriting a
// fixed key) is what actually closes the staleness window on publish.
function themeCssKey(siteId: string, themeId: string, version: number): string {
  return `theme:${siteId}:${themeId}:css:v${version}`
}

// Pre-versioning key format. Any theme published before the `cssVersion` migration has
// its real CSS sitting under this key, not a versioned one — the migration backfills
// `cssVersion` to 0 for existing rows, but there was never a data migration to actually
// move (or copy) the KV content itself to the new `:v0` key, since KV writes can't be
// bundled into a D1 schema migration. Without this fallback, every theme published
// before this change goes dark (getThemeCSS returns null, no CSS is ever injected) the
// moment this code ships, until someone happens to re-publish it.
function legacyThemeCssKey(siteId: string, themeId: string): string {
  return `theme:${siteId}:${themeId}:css`
}

async function getThemeCssVersion(event: H3Event, siteId: string, themeId: string): Promise<number> {
  const db = useDb(event)
  const row = await db.query.themes.findFirst({
    where: and(eq(themes.id, themeId), eq(themes.siteId, siteId)),
    columns: { cssVersion: true },
  })
  return row?.cssVersion ?? 0
}

export async function getThemeCSS(event: H3Event, siteId: string, themeId: string, knownVersion?: number): Promise<string | null> {
  const cached = getCachedThemeCss(siteId, themeId)
  if (cached !== undefined) return cached

  const { kv } = getCfBindings(event)
  if (!kv) return null

  // Callers that already have the theme row in hand (theme-resolver.ts, for the active
  // theme) pass its cssVersion directly to skip this extra lookup; anything else (e.g.
  // resolving a base theme by id alone) falls back to reading it here.
  const version = knownVersion ?? await getThemeCssVersion(event, siteId, themeId)

  let raw = await kv.get(themeCssKey(siteId, themeId, version))
  if (raw === null && version === 0) {
    // Never republished since the versioning migration — fall back to the pre-versioning
    // key. Copy it forward to the versioned key (best-effort; a failure here just means
    // this same fallback runs again next cache-miss, not a functional problem) so future
    // reads hit the fast path and every isolate converges on the same key going forward.
    raw = await kv.get(legacyThemeCssKey(siteId, themeId))
    if (raw !== null) {
      await kv.put(themeCssKey(siteId, themeId, version), raw).catch((err) => {
        console.error('[cf-theme-kv] Failed to copy legacy theme CSS forward to versioned key', err)
      })
    }
  }
  // Sanitize on read too (not just on write) so themes stored before sanitization
  // existed are protected with no data migration — cached sanitized so this cost is
  // paid once per TTL window (60s) instead of on every single SSR request.
  const sanitized = raw !== null ? sanitizeThemeCss(raw) : null
  setCachedThemeCss(siteId, themeId, sanitized)
  return sanitized
}

export async function putThemeCSS(event: H3Event, siteId: string, themeId: string, css: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) throw createError({ statusCode: 503, message: 'CSS themes require a Cloudflare KV namespace (PLUGIN_KV). Configure it in wrangler.toml.' })
  // Sanitize here — the single chokepoint every theme write path (upload, patch,
  // customizer) goes through — so it can never be forgotten by a future call site.
  const sanitized = sanitizeThemeCss(css)

  const db = useDb(event)
  const [row] = await db.update(themes)
    .set({ cssVersion: sql`css_version + 1` })
    .where(and(eq(themes.id, themeId), eq(themes.siteId, siteId)))
    .returning({ cssVersion: themes.cssVersion })
  const version = row?.cssVersion ?? 0

  await kv.put(themeCssKey(siteId, themeId, version), sanitized)
  // Set (not clear) so the publishing isolate's own next render is immediately correct —
  // other isolates still converge via their own cssCache TTL, but each of them now reads
  // a key that has only ever held this new content, so that convergence can never observe
  // a stale value once it happens.
  setCachedThemeCss(siteId, themeId, sanitized)
}

export async function deleteThemeCSS(event: H3Event, siteId: string, themeId: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) return
  const version = await getThemeCssVersion(event, siteId, themeId)
  await kv.delete(themeCssKey(siteId, themeId, version))
  clearCachedThemeCss(siteId, themeId)
}

export async function getThemeDemo(event: H3Event, siteId: string, themeId: string): Promise<string | null> {
  const { kv } = getCfBindings(event)
  if (!kv) return null
  return kv.get(`theme:${siteId}:${themeId}:demo`)
}

export async function putThemeDemo(event: H3Event, siteId: string, themeId: string, json: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) return
  await kv.put(`theme:${siteId}:${themeId}:demo`, json)
}

export async function deleteThemeDemo(event: H3Event, siteId: string, themeId: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) return
  await kv.delete(`theme:${siteId}:${themeId}:demo`)
}
