import type { H3Event } from 'h3'
import { getCfBindings } from './cf-env'

// KVNamespace below is a global ambient type from worker-configuration.d.ts
// (generated by `pnpm run cf-typegen`) — no import needed.

/**
 * Generic read-through cache backed by the `PLUGIN_KV` namespace, for D1-backed lookups
 * that are hot (read on nearly every request), rarely-written, and safe to serve slightly
 * stale for a bounded window — settings resolution and the active-theme-id lookup are the
 * two current callers (see settings.ts / theme-cache.ts). Modeled directly on the existing
 * get/sanitize/cache pattern in cf-theme-kv.ts, generalized to arbitrary JSON-serializable
 * values instead of raw theme CSS text.
 *
 * Intended layering (this helper is only the middle layer):
 *   1. Caller-managed isolate-memory cache (fastest, checked by the caller BEFORE calling
 *      this function at all — a hit here should never even reach this module). Kept
 *      caller-side rather than folded into this helper because each caller's isolate
 *      cache stores a differently-shaped value than what belongs in shared KV: settings.ts
 *      caches the final *decrypted* value in isolate memory but must only ever persist the
 *      raw (still-encrypted, for sensitive keys) DB value to this shared KV layer — caching
 *      plaintext secrets in a second, shared store would widen their exposure beyond what's
 *      already stored at rest in D1. Forcing that distinction through a single generic
 *      "isolate + KV" helper would make the safe path easy to get wrong; keeping isolate
 *      caching explicit at each call site keeps that decision visible.
 *   2. This KV layer (this function) — a network hop, but far cheaper than D1 and shared
 *      across every isolate, so a cold isolate/new colo doesn't pay a full D1 round trip.
 *   3. `load()` — the authoritative D1 (or other durable-store) read, last resort.
 *
 * `load()` returning `null` is cached as the literal JSON `null` (distinguishable from a
 * true KV miss, which returns the real JS `null` from `kv.get()` before any JSON.parse
 * happens) — this makes "definitively absent" a cacheable state too, e.g. a setting key
 * with no row at all, so a cold isolate doesn't re-hit D1 on every request for a key that
 * legitimately doesn't exist. Mirrors theme-cache.ts's existing convention of caching "no
 * active theme" as `null` rather than leaving it permanently uncached.
 *
 * A KV read or write failure never breaks the caller: both are wrapped, logged, and fall
 * through to `load()` (read failure) or are simply skipped (write failure) — same
 * error-handling philosophy as `withEdgeCache` in edge-cache.ts. `load()` itself is NOT
 * wrapped here — a failure there is the authoritative source failing and must propagate.
 *
 * The `PLUGIN_KV` binding may be absent entirely (local dev without it configured, most
 * unit/integration tests) — `getCfBindings(event)` returns `kv: null` in that case, and
 * this function falls straight through to `load()` with no KV interaction attempted.
 */
export async function kvReadThrough<T>(
  event: H3Event,
  key: string,
  ttlSeconds: number,
  load: () => Promise<T | null>,
): Promise<T | null> {
  const { kv } = getCfBindings(event)

  if (kv) {
    try {
      const raw = await kv.get(key)
      if (raw !== null) {
        return JSON.parse(raw) as T
      }
    } catch (err) {
      console.error(`[kv-cache] read failed for "${key}", falling back to load()`, err)
    }
  }

  const loaded = await load()

  if (kv) {
    try {
      // Cloudflare KV requires expirationTtl >= 60 seconds; callers must pass at least
      // that. Rare writes vs. frequent reads is exactly the profile this is for (per
      // CLAUDE.md's KV rate-limit note: ~1 write/sec/key) — a put() per cold-isolate
      // read, not per request, since a warm isolate never gets past the isolate cache
      // the caller checks before this function is ever invoked.
      await kv.put(key, JSON.stringify(loaded), { expirationTtl: ttlSeconds })
    } catch (err) {
      console.error(`[kv-cache] write failed for "${key}"`, err)
    }
  }

  return loaded
}

/**
 * Invalidates a KV-cached entry immediately on write, rather than waiting out its TTL —
 * the same "write must be visible to other isolates promptly" requirement `putThemeCSS`
 * solves with a versioned key (see cf-theme-kv.ts). A plain delete-then-repopulate is
 * sufficient here (unlike theme CSS content): the values behind these keys are small and
 * cheap to reconstruct from D1 on the very next read, so there's no equivalent of theme
 * CSS's ~2-minute uneven-visibility window worth avoiding with key-versioning — the only
 * staleness risk after a delete is the single next reader paying one extra D1 round trip
 * per site/isolate, not stale content being served.
 *
 * A delete failure is logged and swallowed, never thrown — the D1 write that prompted this
 * call already committed; a cache invalidation failing must not fail the mutation itself.
 */
export async function kvCacheDelete(event: H3Event, key: string): Promise<void> {
  const { kv } = getCfBindings(event)
  if (!kv) return
  try {
    await kv.delete(key)
  } catch (err) {
    console.error(`[kv-cache] delete failed for "${key}"`, err)
  }
}
