export * from './types'
export * from './blocks/definitions'
export { useCanvas } from './editor/useCanvas'
export { useAiImprove, AI_IMPROVE_ACTIONS } from './editor/useAiImprove'
export type { AiInstruction, AiImproveAction } from './editor/useAiImprove'

// Vue components
export { default as CanvasContentEditor } from './editor/CanvasContentEditor.vue'
export { default as CanvasBlockHero } from './blocks/CanvasBlockHero.vue'
export { default as CanvasBlockText } from './blocks/CanvasBlockText.vue'
export { default as CanvasBlockImage } from './blocks/CanvasBlockImage.vue'
export { default as CanvasBlockColumns } from './blocks/CanvasBlockColumns.vue'
export { default as CanvasBlockContainer } from './blocks/CanvasBlockContainer.vue'
export { default as CanvasBlockCta } from './blocks/CanvasBlockCta.vue'
export { default as CanvasBlockSpacer } from './blocks/CanvasBlockSpacer.vue'
export { default as CanvasBlockVideo } from './blocks/CanvasBlockVideo.vue'
export { default as CanvasBlockTestimonial } from './blocks/CanvasBlockTestimonial.vue'
export { default as CanvasBlockFeatures } from './blocks/CanvasBlockFeatures.vue'
export { default as CanvasBlockGdpr } from './blocks/CanvasBlockGdpr.vue'
export { default as CanvasBlockFooter } from './blocks/CanvasBlockFooter.vue'
export { default as CanvasBlockButton } from './blocks/CanvasBlockButton.vue'
export { default as CanvasBlockAccordion } from './blocks/CanvasBlockAccordion.vue'
export { default as CanvasBlockPricing } from './blocks/CanvasBlockPricing.vue'
export { default as CanvasBlockGallery } from './blocks/CanvasBlockGallery.vue'
export { default as CanvasBlockCarousel } from './blocks/CanvasBlockCarousel.vue'
export { default as CanvasBlockCalendar } from './blocks/CanvasBlockCalendar.vue'
export { default as HtmlBlock } from './blocks/HtmlBlock.vue'
export { default as CanvasAdmin } from './admin/CanvasAdmin.vue'
