// App-specific typing glue for Cloudflare bindings. The Cloudflare-native primitives
// (KVNamespace, D1Database, WorkerLoader/WorkerLoaderWorkerCode, SendEmail, etc.) are NOT
// declared here — they come from the official runtime types in
// `server/types/worker-configuration.d.ts`, generated by `pnpm run cf-typegen` (wrapping
// `wrangler types`) from wrangler.toml. Re-run that command after changing wrangler.toml
// bindings or .env vars. This file only covers what wrangler types cannot know about:
// NuxFlow's own custom service-binding RPC surface, and the H3 event context augmentation
// that wires the two together.

export interface NuxFlowCloudflareEnv {
  PLUGIN_KV: KVNamespace
  LOADER: WorkerLoader
  DB?: D1Database
  AE?: AnalyticsEngineDataset
  EMAIL?: SendEmail
  /** Optional R2 bucket for the native media storage provider (server/utils/media-providers/r2.ts). */
  MEDIA_BUCKET?: R2Bucket
  /** Optional Workers AI binding — zero-config AI provider (server/utils/cf-env.ts's getWorkersAiBinding). */
  AI?: Ai
  /** Optional Vectorize index for semantic search / RAG embeddings (server/utils/cf-env.ts's getVectorizeIndex). */
  VECTORIZE?: VectorizeIndex
  [key: string]: unknown
}

declare module 'h3' {
  interface H3EventContext {
    cloudflare?: {
      env: NuxFlowCloudflareEnv
      request: Request
      ctx: { waitUntil(promise: Promise<unknown>): void }
    }
  }
}
